//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ref_string&quot;: &quot;SilveIT&quot;,
        ///  &quot;id&quot;: 1337,
        ///  &quot;email&quot;: &quot;ModdedBy@SilveIT&quot;,
        ///  &quot;mode&quot;: {
        ///    &quot;name&quot;: &quot;unlimited&quot;,
        ///    &quot;props&quot;: &quot;&quot;
        ///  },
        ///  &quot;team&quot;: {
        ///    &quot;name&quot;: &quot;SilveIT&quot;,
        ///    &quot;id&quot;: 1337
        ///  },
        ///  &quot;settings&quot;: {
        ///    &quot;nc_out&quot;: {
        ///      &quot;minutes_settings&quot;: {
        ///        &quot;balance&quot;: 1337
        ///      },
        ///      &quot;headset_vc&quot;: {
        ///        &quot;available&quot;: true
        ///      },
        ///      &quot;state&quot;: &quot;user_choice&quot;
        ///    },
        ///    &quot;nc_in&quot;: {
        ///      &quot;state&quot;: &quot;user_choice&quot;
        ///    },
        ///    &quot;update&quot;: {
        ///      &quot;prevent_update&quot;: &quot;true&quot;,
        ///      &quot;availa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserProfileInfo {
            get {
                return ResourceManager.GetString("UserProfileInfo", resourceCulture);
            }
        }
    }
}
